# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='multiple_files',
            field=models.BooleanField(default=False, verbose_name='Le fichier contient plusieurs annonces ?'),
        ),
    ]
