# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20170513_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début du contrat'),
        ),
    ]
