# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20170513_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='url_annonce',
            new_name='url',
        ),
    ]
