# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechercheFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(blank=True, max_length=40, verbose_name=b"Nom de l'entreprise")),
                ('domain', models.ManyToManyField(blank=True, null=True, to='post.Domaine', verbose_name=b'Domaine concern\xc3\xa9')),
                ('duree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Duree', verbose_name=b'Dur\xc3\xa9e du contrat')),
                ('type_de_contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.TypeContrat', verbose_name=b'Nature du contrat')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Zone', verbose_name=b'Zone g\xc3\xa9ographique')),
            ],
        ),
    ]
