# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherchefields',
            name='domain',
            field=models.ManyToManyField(blank=True, to='post.Domaine', verbose_name=b'Domaine concern\xc3\xa9'),
        ),
    ]
