# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160128_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recherchefields',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='recherchefields',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='recherchefields',
            name='type_de_contrat',
        ),
        migrations.RemoveField(
            model_name='recherchefields',
            name='zone',
        ),
        migrations.DeleteModel(
            name='RechercheFields',
        ),
    ]
