#!/usr/bin/env python
# -*- coding: utf-8 -*-

import ldap

from stages.settings_local import *

"""
Django settings for stages project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Config relative au SSL pour le HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Config pour Django-auth-ldap
AUTH_LDAP_ADMIN_SERVER_URI = "ldap://ldap.resel.fr:389"
AUTH_LDAP_ADMIN_BIND_DN = ""
AUTH_LDAP_ADMIN_BIND_PASSWORD = ""
AUTH_LDAP_ADMIN_USER_DN_TEMPLATE = "uid=%(user)s,ou=admins,dc=resel,dc=enst-bretagne,dc=fr"
AUTH_LDAP_ADMIN_START_TLS = True

AUTH_LDAP_USERS_SERVER_URI = "ldap://ldap.resel.fr:389"
AUTH_LDAP_USERS_BIND_DN = ""
AUTH_LDAP_USERS_BIND_PASSWORD = ""
AUTH_LDAP_USERS_USER_DN_TEMPLATE = "uid=%(user)s,ou=people,dc=maisel,dc=enst-bretagne,dc=fr"
AUTH_LDAP_USERS_START_TLS = True

# Config pour Django-cas-ng
CAS_SERVER_URL = "https://login.telecom-bretagne.eu/cas/"
CAS_REDIRECT_URL = "/"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'stages.auth_ldap.LDAPBackendAdmin',
    'stages.auth_ldap.LDAPBackendUsers',
    'django_cas_ng.backends.CASBackend',
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Config pour l'envoi de mails
SERVER_EMAIL = 'stages-bot@resel.fr'
EMAIL_USE_TLS = True
EMAIL_HOST = 'pegase.adm.resel.fr'
EMAIL_SUBJECT_PREFIX = ''

ADMINS = [
    ('ML de stages', 'stages-admin@resel.fr'),
]

ALLOWED_HOSTS = ['stages.resel.fr']

# Pour le login et logout
LOGIN_URL = '/login'
LOGOUT_URL = '/logout'
LOGIN_REDIRECT_URL = '/'

# Expiration de session pour les users connectés
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

DEFAULT_CHARSET = 'utf-8'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stages',
    'post',
    'search',
    'django_cleanup',
    'django_cas_ng',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'stages.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), '/var/www/stages/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stages.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "sfiles"),
)

# Media files (upload d'annonces au format .pdf ou .txt)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
